name: Update METAR Map

on:
  schedule:
    - cron: '0 * * * *'  # 1時間おきに実行
  workflow_dispatch:      # 手動実行ボタンを有効にする

# ページ公開に必要な権限を設定
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install folium requests

      - name: Run script
        run: python metarman.py

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'  # index.htmlがある場所を指定

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
